name: github pages

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 23

    - name: Build
      env: 
        TZ: "Asia/Tokyo"
      run: |
        cd ./book
        npm i
        npx honkit build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./book/_book
        publish_branch: gh-pages
        user_name: 'ai[bot]'
        user_email: '138105980+yui-syui-ai[bot]@users.noreply.github.com'
